sudo: required
services:
- rabbitmq
language: python
matrix:
  include:
    - name: "Python 2.7 on Linux"
      os: linux
      python: 2.7
      env: TOXENV=py27

    - name: "Python 3.5 on Linux"
      os: linux
      python: 3.5
      env: TOXENV=py35

install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  skip_existing: true
  on:
    tags: true
  user: labviros
  password:
    secure: IkaSIydrK7sVow9WyZeI29YNMdYsieY1KN1BWYWyu7/we8dIKCJddjvdnqFOO8VDnD+gsoVFDWkzhlZqKC3YbFNBpO0a8bvdaHHr0yJs6GxsZMMSYys5iYHZUrtPGYQQ/dsjy6cSjqLvgGMBBdEsFODR7Yj2bwh+P1jZ8+MGhzqh3xm18yLe00K/W45OyWjg+g0cwYmjaFW9VIVXqJQMNplzCSKv5clezb3ymURmIU6jyQFJ994o3NjNMQeC6rRMxec4gKoVZnGK8Yxkul35DCafBFHeQVCzLp2Aa/+8RobRe8RVsyP/ko4k9LxZV6OsOrFuu6ylicBqkbc2RI5uPs7rpHJEaaNv3apSvY6im46grVfB//BmBL2R7i4q5VLnR0f3/vWzSVscDoIbJwGgAwrRp+r2wicV74Z6vp+xNP3/LqJ3Eqd4uNNjGyxeUuihAUHz4MsNBYSSNtu/qNKiPH0jKdNLrGl1P5KgDhKb9wZK6agUWmtx9O7GLxlO7vvNqyzydbeFKCLYe0LTWVpQHftuR7kReLZtsTCI1eOozAjMuwpv0CVhKjc6hWkNWeencqhAk7u+vdnekj99nQURQNRr+ivDP6atlMANP2knXy85oqAs7W9pw/JolxJVwGdlkrYr8OuaM67F1cR2RvyiWsOvgI14hgOch38N3E1TUKQ=
