sudo: required
services:
- rabbitmq
language: python
matrix:
  include:
    - name: "Python 2.7 on Linux"
      os: linux
      python: 2.7
      env: TOXENV=py27

    - name: "Python 3.5 on Linux"
      os: linux
      python: 3.5
      env: TOXENV=py35

    - name: "Python 3.5 on Windows"
      os: windows 
      language: sh # 'language: python' is an error on Travis CI Windows
      before_install: 
        - choco install python --version 3.5.4
        - python -m pip install --upgrade pip
      env: 
        - TOXENV=py35
        - PATH=/c/Python35:/c/Python35/Scripts:$PATH
        - secure: HwqK7WxcO+lAt8Al6AmCsprjLv5FQA0QFOKH2qpEz+DSg3oKwrjCFiJ7LILGTTAx3Al5eCGqM7egdZV0T52OfycGAtWtC8LKBTZmg0OLRPcYoT1U4T4othapxOQgVgAT8ase3j0VmVnbNKGud+2gSgFCAdYtClXZ4NZkWO5BwH20rFT7UJsvYa4l2zmpK3/buVpUrZqrASPWgaJGSFD5T85OXh3RAYD4QsiLQ8Q92qI6/lx/8Tsj+b0t5LEevXk+D4IEQaedij5YiQQ+S0hlGxDtTs4trkoxj+M7mtUwn6GPcgjBQtXFjB6vnN1bgYl7hHlQc5BWm5L20MJOOE++SsmX2WL156slWCkTjbYAXRt1ogmFPCqEkynC8fNfqJ0k+7SzECQzbWgo70dnnsELxws1km4cHYjWVJocqKpOuLRMlexIB0+5Pg7zaetzaMTmzu3tEb0Y1eNjvmS/mTPBNBcnXaeFj0L7gi2dZceUwPdF9usKXZZuz2JgsAwzFl+3mwjI8jLvwWpJzWe27fyKTVL56yeQcNQGgnYJJ626049o5MORO/LbVW4F6Fpnhl1UvqMEJLJ6Ts/wlR/pXg9LoVBapPyVYrqnxHi5Hlzk9COMVDo+LYh+Xdag532UbKkh9x+MfGFn+rUeL9kZJyGCPzD30xY1JvrfQ8ndxqIdZ1o=

install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  on:
    tags: true
  user: labviros
  password:
    secure: GyhFCKylrbBy51+ZUHm5Yqz46CjWH4RPtRjOlYWj4CXIAz/KrDon0TmACPlqhdtjZ+fmaELRti2/88ytYhGxZDA6a/j2KC/b5yBywJpoP/aBQIrntLibV2ZUphpzTsArot+ytcgdy2JJ6QXVCdkaw6j8YodLuiOdhCgvEXCU9a8BYh6QDesg++GARVPxQwr/Hmxmm64lTy+Seji6O4D4ruJ2rnz559L5/hYfm5I/VrdlASQACuO1xAB8RwtLZW4cLynXNlUeC6KUPJQR/jGhUb8i51ysGDubdK9i0/UFsVVOhQ/vHc3KVFlvoVy65oQ8OoRfOfZ4MTbKBJKydp6i5VWJSzlJM8Rup6a7x4l/0DRa+p79dvIsGd/MaEiwfqNUGrsuRYFBmwdLrHTpjee404H264nLER5hOZbDn8b5KSQd02Yre7VeTAuwGxg/G78eVKM4ob6lrYukw/Ys1TV124TjErsA0DRiRh2gvp8HUXygzjph7UHlb+toGwNU2wEFRsBaZM/4TQU7NTpApkIniq6XFNhledZZdSNNa7WS4TkTiaRDPanvcpL6qXHH8JnmOQiNhY2XBg3BjlYDx7t0loxc96r/fD0O57H4pbGKb/3aRj8tzo3zpOOtKmMqVaBKauGZ5Xju+HRmdlWnpTcyygAKyjeRNlkek9fbugvj+BI=
