sudo: required
services:
- rabbitmq
language: python
python:
- '2.7'
- '3.5'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  on:
    tags: true
  user: labviros
  password:
    secure: GyhFCKylrbBy51+ZUHm5Yqz46CjWH4RPtRjOlYWj4CXIAz/KrDon0TmACPlqhdtjZ+fmaELRti2/88ytYhGxZDA6a/j2KC/b5yBywJpoP/aBQIrntLibV2ZUphpzTsArot+ytcgdy2JJ6QXVCdkaw6j8YodLuiOdhCgvEXCU9a8BYh6QDesg++GARVPxQwr/Hmxmm64lTy+Seji6O4D4ruJ2rnz559L5/hYfm5I/VrdlASQACuO1xAB8RwtLZW4cLynXNlUeC6KUPJQR/jGhUb8i51ysGDubdK9i0/UFsVVOhQ/vHc3KVFlvoVy65oQ8OoRfOfZ4MTbKBJKydp6i5VWJSzlJM8Rup6a7x4l/0DRa+p79dvIsGd/MaEiwfqNUGrsuRYFBmwdLrHTpjee404H264nLER5hOZbDn8b5KSQd02Yre7VeTAuwGxg/G78eVKM4ob6lrYukw/Ys1TV124TjErsA0DRiRh2gvp8HUXygzjph7UHlb+toGwNU2wEFRsBaZM/4TQU7NTpApkIniq6XFNhledZZdSNNa7WS4TkTiaRDPanvcpL6qXHH8JnmOQiNhY2XBg3BjlYDx7t0loxc96r/fD0O57H4pbGKb/3aRj8tzo3zpOOtKmMqVaBKauGZ5Xju+HRmdlWnpTcyygAKyjeRNlkek9fbugvj+BI=
