# Adapted from https://github.com/ogrisel/python-appveyor-demo/

image: Visual Studio 2017
# Windows build and test of Pika
environment:
  matrix:
    - TOXENV: 'py27'
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'

    - TOXENV: 'py27'
      TOXPYTHON: C:\Python27-x64\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\Python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'

    - TOXENV: 'py35'
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'

    - TOXENV: 'py35'
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'

cache:
  - '%LOCALAPPDATA%\pip\Cache'

build: false

init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*

before_test:
  # PowerShell script adapted from https://gist.github.com/FeodorFitsner/06b377df42ba8f398909
  - ps: 'C:\projects\is-wire-py\ci-data\appveyor\install-rabbitmq.ps1'

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip install --upgrade pip"
  - pip install tox tox-appveyor
  - pip install -r requirements-test.txt"


test_script:
  - tox